// Full cinematic walkthrough — every meaningful feature gets a highlight.
// Sourced from an exhaustive read-only scan of poster-session-app on 2026-04-14.
// Runs ~7 minutes end-to-end; viewer can tab-jump anywhere to skip.

export const TIMELINE = [
  // ═══ 0. Cold open ═══════════════════════════════════════════
  { t: 0, type: 'title-card',
    lines: ['NERPG Spring 2026', 'UConn · 117 attendees · 23 posters · 108 votes'],
    sub: 'Let it play · touch to pause · tabs to jump · designed for phones',
    duration: 5200 },

  // ═══ 1. Check-in / welcome tutorial ═════════════════════════
  { t: 5200,  type: 'mode', mode: 'gallery' },
  { t: 5700,  type: 'scene-card', text: '1.  Checking in', duration: 1600 },
  { t: 7400,  type: 'welcome' },

  { t: 10500, type: 'highlight', selector: '.welcome-fact__code', position: 'bottom',
    label: 'your codename',
    text: 'Every attendee\u2019s identity is a polymer-themed codename. No email, no password, no account creation.',
    duration: 5200 },
  { t: 15900, type: 'highlight', selector: '.welcome-fact__text', position: 'bottom',
    label: 'your polymer fact',
    text: 'Printed on the badge: a keepsake fact tied to your domain. Becomes trivia material at the end.',
    duration: 5200 },
  { t: 21300, type: 'highlight', selector: '.welcome-step:nth-of-type(1) .welcome-step__title', position: 'right',
    label: 'step 1 \u2014 visit',
    text: 'Attendees walk the gallery and note poster numbers. Presenters carry theirs on a small card.',
    duration: 4500 },
  { t: 26000, type: 'highlight', selector: '.welcome-step:nth-of-type(2) .welcome-step__title', position: 'right',
    label: 'step 2 \u2014 log',
    text: 'One tap records the visit. Offline-first \u2014 stored locally, synced when the signal returns.',
    duration: 4500 },
  { t: 30700, type: 'highlight', selector: '.welcome-step:nth-of-type(3) .welcome-step__title', position: 'right',
    label: 'step 3 \u2014 vote',
    text: 'Voting unlocks after 3 visits. Rank your top 3 \u2014 weighted 3\u20132\u20131.',
    duration: 4500 },
  { t: 35300, type: 'highlight', selector: '.welcome-btn', position: 'top',
    label: 'dismiss',
    text: 'First-time-only tutorial. Replay any time via the "How it works" pill in the header.',
    duration: 4000 },

  { t: 39500, type: 'dismiss-welcome' },

  // ═══ 2. Gallery overview ════════════════════════════════════
  { t: 40300, type: 'scene-card', text: '2.  The gallery', duration: 1600 },
  { t: 42100, type: 'highlight', selector: '.identity-chip', position: 'bottom',
    label: 'who you are',
    text: 'Codename, first name, deterministic avatar color. Same code always renders the same color across devices.',
    duration: 4500 },
  { t: 46800, type: 'highlight', selector: '.gallery-search__input', position: 'bottom',
    label: 'search',
    text: 'Fuzzy search by title, author, advisor, keyword, or poster number.',
    duration: 4000 },
  { t: 51000, type: 'highlight', selector: '.visit-progress', position: 'bottom',
    label: 'progress',
    text: 'Live "N of 3 to unlock voting" bar. Glows gold the instant voting unlocks.',
    duration: 4500 },
  { t: 55700, type: 'highlight', selector: '.gallery-pulse', position: 'top',
    label: 'live pulse',
    text: 'Real-time count of every visit across the room. Supabase realtime \u2014 no polling.',
    duration: 4500 },
  { t: 60400, type: 'highlight', selector: '.poster-card', position: 'right',
    label: 'poster card',
    text: 'Every card: headshot, title, presenter-written blurb. Tap to open the full abstract + log a visit.',
    duration: 4800 },
  { t: 65300, type: 'highlight', selector: '.quick-log-fab', position: 'top',
    label: 'quick-log',
    text: 'Power-user path: tap the floating button, punch the poster number on a numpad. Haptic on every key.',
    duration: 4800 },
  { t: 70300, type: 'feed', actor: '_rand_', action: 'opened poster #7 \u2014 Cannabinoid antimicrobial SAR' },
  { t: 72600, type: 'feed', actor: '_rand_', action: 'logged a visit from Jonal Labs' },
  { t: 73800, type: 'narrator', duration: 4500,
    text: 'Spring 2026 stat: app absorbed 106 Wi-Fi flips \u2014 41% of visits logged offline, 0 data loss.' },

  // ═══ 3. Poster modal deep dive ══════════════════════════════
  { t: 74900, type: 'scene-card', text: '3.  Inside a poster card', duration: 1700 },
  { t: 76700, type: 'open-modal', poster: 13 },
  { t: 78200, type: 'highlight', selector: '.modal__headshot', position: 'right',
    label: 'presenter',
    text: 'Photo + advisor. If no headshot, colored initials keyed from a hash of the name \u2014 never blank.',
    duration: 4700 },
  { t: 83100, type: 'highlight', selector: '.poster-modal__summary', position: 'bottom',
    label: 'short blurb',
    text: 'Presenter-written hook. We never auto-generate \u2014 the author\'s voice stays the author\'s voice.',
    duration: 5000 },
  { t: 88300, type: 'highlight', selector: '.poster-modal__abstract-toggle', position: 'bottom',
    label: 'read abstract',
    text: 'Full abstract hidden by default to keep cards scannable. One tap expands.',
    duration: 4800 },
  { t: 93300, type: 'highlight', selector: '.modal__notes--promoted', position: 'top',
    label: 'your notes',
    text: 'Jot questions, follow-up ideas, or intros. Saved to this device. Exportable from the gallery.',
    duration: 5500 },
  { t: 99000, type: 'highlight', selector: '.modal__log-visit', position: 'top',
    label: 'log visit',
    text: 'Counts toward your 3 to unlock voting. Works offline \u2014 the modal never blocks on a network call.',
    duration: 5000 },
  { t: 104200, type: 'close-modal' },
  { t: 105000, type: 'narrator', duration: 4500,
    text: 'Same card design on gallery, vote ballot, and confirm \u2014 one mental model across the event.' },

  // ═══ 4. Ranked ballot ═══════════════════════════════════════
  { t: 110000, type: 'mode', mode: 'vote' },
  { t: 110500, type: 'scene-card', text: '4.  Ranked ballot', duration: 1700 },
  { t: 112300, type: 'narrator', trackAware: true, duration: 5500,
    text: 'Ranked voting (3\u20132\u20131). You\u2019re voting in the {track}.' },
  { t: 118000, type: 'highlight', selector: '.vote-instructions', position: 'bottom',
    label: 'instructions',
    text: 'Three-step instructions stay pinned above the grid until you\'ve ranked all three.',
    duration: 5000 },
  { t: 123200, type: 'narrator', duration: 5000,
    text: 'Distinguished Poster (industry panel + cash prize) and Peer Impact (peer panel) run in parallel.' },
  { t: 128500, type: 'highlight', selector: '.poster-card', position: 'right',
    label: 'tap to rank',
    text: 'Tap once = 1st pick, again = 2nd, again = 3rd. Tap a picked card to drop it. Max 3.',
    duration: 5000 },
  { t: 133700, type: 'narrator', duration: 4500,
    text: 'Server enforces the weighting: 3 points for 1st, 2 for 2nd, 1 for 3rd. Same SQL for both tracks.' },
  { t: 138500, type: 'narrator', duration: 4500,
    text: 'Spring 2026: 34% of voters changed their mind before submitting. The ballot is designed for that.' },

  // ═══ 5. Confirm / schedule / stats ══════════════════════════
  { t: 138500, type: 'mode', mode: 'confirm' },
  { t: 139000, type: 'scene-card', text: '5.  Thanks + stay-for-the-ceremony', duration: 1700 },
  { t: 140800, type: 'highlight', selector: '.confirm-check', position: 'bottom',
    label: 'success moment',
    text: 'Animated checkmark + confetti. Small delight after voting.',
    duration: 4500 },
  { t: 145500, type: 'narrator', duration: 4500,
    text: 'Attendees see the schedule, their ranked picks, and live event stats \u2014 a reason to stay seated.' },
  { t: 150300, type: 'highlight', selector: '#confirm-stats', position: 'top',
    label: 'event pulse',
    text: 'Three live stats that refresh every 30 seconds. Posters explored, total visits today, votes cast.',
    duration: 5000 },
  { t: 155500, type: 'feed', actor: '_rand_', action: 'submitted their ranked ballot' },
  { t: 157800, type: 'feed', actor: '_rand_', action: 'deep-dwelled 869s on poster #3' },
  { t: 160100, type: 'feed', actor: '_rand_', action: 'voted from Jonal Labs' },

  // ═══ 6. Admin dashboard ═════════════════════════════════════
  { t: 162500, type: 'mode', mode: 'admin' },
  { t: 163000, type: 'scene-card', text: '6.  The admin\u2019s view', duration: 1800 },
  { t: 164800, type: 'narrator', duration: 5000,
    text: 'Admin sees the whole event live. No polling on this page \u2014 every visit and vote streams in via Supabase realtime.' },
  { t: 170000, type: 'highlight', selector: '#phase-toggle', position: 'bottom',
    label: 'phase toggle',
    text: 'Two phases: Session (voting open) and Results. Flipping to Results triggers a 45-second grace period plus a live celebration on every phone.',
    duration: 6000 },
  { t: 176200, type: 'narrator', duration: 4500,
    text: 'The phase flip is one SQL UPDATE on event_state. Postgres logical replication broadcasts it to every connected phone.' },
  { t: 181000, type: 'highlight', selector: '#stats-grid', position: 'bottom',
    label: 'live stats',
    text: 'Check-ins, visits, voters \u2014 auto-updating via realtime. No refresh.',
    duration: 4700 },
  { t: 185800, type: 'highlight', selector: '#attendee-list-container', position: 'top',
    label: 'attendees',
    text: 'Grouped by role. Inline rename for walk-ups ("Voter 42" \u2192 real name). Per-attendee vote reset if someone messed up.',
    duration: 5500 },
  { t: 191400, type: 'narrator', duration: 4500,
    text: 'Row-level security: attendees can\u2019t read each other\u2019s ballots. Admin actions gated by SECURITY DEFINER RPCs, role-checked server-side.' },
  { t: 196200, type: 'highlight', selector: '#results-container', position: 'top',
    label: 'live tallies',
    text: 'Two weighted tables: Distinguished + Peer Impact. Ties break on deepest support first.',
    duration: 5200 },
  { t: 201600, type: 'narrator', duration: 4500,
    text: 'Both tallies are SQL functions, not client math. 45-second grace + weighted scores \u2014 enforced by Postgres, unspoofable from the client.' },
  { t: 206300, type: 'highlight', selector: '#schedule-editor', position: 'top',
    label: 'schedule editor',
    text: 'Running late? Update the schedule here, every attendee sees the new times within seconds.',
    duration: 5000 },
  { t: 211500, type: 'highlight', selector: '#admin-feed', position: 'top',
    label: 'activity feed',
    text: 'Every visit + every vote, live. Votes batched 300ms so you see "Jane voted 1st/2nd/3rd" as one line.',
    duration: 5500 },
  { t: 217200, type: 'narrator', duration: 5000,
    text: 'Stack: Supabase Postgres + realtime. Free tier handles a 150-person event. Paid tier ($25/mo) covers a year of events. No per-attendee fees.' },
  { t: 222400, type: 'narrator', duration: 4500,
    text: 'Full event footprint: <10 MB per event including every visit and vote. A hundred events archive in a few hundred MB.' },
  { t: 227100, type: 'feed', actor: '_rand_', action: 'voted (Peer Impact)' },
  { t: 229400, type: 'feed', actor: '_rand_', action: 'added a note to poster #18' },
  { t: 231700, type: 'feed', actor: '_rand_', action: 'logged 16 visits total' },

  // ═══ 7. Phase flip + 45s grace ══════════════════════════════
  { t: 234500, type: 'narrator', kind: 'gold', duration: 3500,
    text: 'All 108 votes in \u2014 time to close voting.' },
  { t: 238300, type: 'scene-card', text: '7.  Closing the ceremony', duration: 1700 },
  { t: 240100, type: 'narrator', duration: 4500,
    text: '45-second grace after the flip \u2014 nobody mid-vote loses their ballot. Server-enforced.' },
  { t: 244700, type: 'mode', mode: 'results' },
  { t: 245300, type: 'confetti' },

  // ═══ 8. Results podium ══════════════════════════════════════
  { t: 246500, type: 'scene-card', text: '8.  Winners \u2014 live', duration: 1800 },
  { t: 248500, type: 'narrator', kind: 'gold', duration: 5000,
    text: '\ud83c\udfc6 Distinguished Poster #1: Zhiming Li (#13) \u2014 17 points (4\u00d71st \u00b7 2\u00d72nd \u00b7 1\u00d73rd).' },
  { t: 253700, type: 'highlight', selector: '.podium__slot--1', position: 'bottom',
    label: 'gold pedestal',
    text: 'Staggered reveal \u2014 3rd place first, then 2nd, then 1st at the 3-second mark. Confetti sync\'d to the top slot.',
    duration: 5500 },
  { t: 259300, type: 'highlight', selector: 'hr.results-divider', position: 'bottom',
    label: 'two tracks',
    text: 'Below the first podium: the Peer Impact section. Both tracks render at the same moment on every attendee\u2019s phone.',
    duration: 5500 },
  { t: 264900, type: 'narrator', kind: 'gold', duration: 5000,
    text: '\ud83c\udfc6 Peer Impact #1: Mohak Desai (#22) \u2014 15 points (5\u00d71st-place).' },
  { t: 270000, type: 'narrator', duration: 4500,
    text: 'Both celebrations + confetti fire live. No refresh. No polling.' },

  // ═══ 9. Trivia \u2014 keepsake callback ═══════════════════════════
  { t: 274700, type: 'scene-card', text: '9.  Trivia \u2014 the facts come back', duration: 1800 },
  { t: 276500, type: 'narrator', duration: 4000,
    text: 'Every polymer fact printed at check-in becomes a trivia question. Engagement that travels past the session.' },
  { t: 280700, type: 'trivia' },

  // ═══ 10. CTA \u2014 Formspree ═════════════════════════════════════
  // Trivia pauses the timer. CTA fires when trivia completes.
  { t: 281000, type: 'cta-overlay' },
  { t: 600000, type: 'loop' },
]
